[data_source]
name = "akeyless_account_custom_fields"
description = "List account custom fields"

[read]
endpoint = "/account-custom-field-list"
schema = "accountCustomFieldList"

[fields]
token = { skip = true }
