[data_source]
name = "akeyless_dynamic_secrets"
description = "List all dynamic secret producers"

[read]
endpoint = "/dynamic-secret-list"
schema = "dynamicSecretList"

[fields]
token = { skip = true }
