[data_source]
name = "akeyless_gateway_rotated_secrets"
description = "List gateway rotated secrets"

[read]
endpoint = "/gateway-list-rotated-secrets"
schema = "GatewayListRotatedSecrets"

[fields]
token = { skip = true }
