[data_source]
name = "akeyless_gateway_migrations"
description = "List gateway migrations"

[read]
endpoint = "/gateway-list-migration"
schema = "gatewayListMigration"

[fields]
token = { skip = true }
