[provider]
name = "akeyless"
description = "Akeyless Vault Provider — manage secrets, auth methods, targets, and roles"
version = "1.0.0"
sdk_import = "github.com/akeylesslabs/akeyless-go/v5"

[auth]
token_field = "token"
env_var = "AKEYLESS_ACCESS_TOKEN"
gateway_url_field = "api_gateway_address"
gateway_env_var = "AKEYLESS_GATEWAY"

[defaults]
skip_fields = [
  "token",
  "uid-token",
  "json",
  "password",
  "username",
  "metadata",
  "multiline_value",
  "inject-url",
  "secure-access-enable",
  "secure-access-url",
  "secure-access-web",
  "secure-access-web-browsing",
  "secure-access-web-proxy",
  "secure-access-host",
  "secure-access-rdp-user",
  "secure-access-rdp-domain",
  "secure-access-ssh-creds",
  "secure-access-ssh-creds-user",
  "secure-access-ssh",
  "secure-access-bastion-issuer",
  "secure-access-certificate-issuer",
  "secure-access-gateway",
  "secure-access-bastion-api",
  "secure-access-bastion-ssh",
  "secure-access-api",
  "secure-access-allow-external-user",
  "secure-access-aws-account-id",
  "secure-access-aws-native-cli",
  "secure-access-db-name",
  "secure-access-db-schema",
  "secure-access-disable-concurrent-connections",
  "secure-access-enforce-hosts-restriction",
  "secure-access-use-internal-bastion",
  "secure-access-ssh-user",
]
