[resource]
name = "akeyless_group"
description = "Manages a group in Akeyless Vault"
category = "misc"

[crud]
create_endpoint = "/create-group"
create_schema = "createGroup"
update_endpoint = "/update-group"
update_schema = "updateGroup"
read_endpoint = "/get-group"
read_schema = "getGroup"
read_response_schema = "GetGroupOutput"
delete_endpoint = "/delete-group"
delete_schema = "deleteGroup"

[identity]
id_field = "name"
import_field = "name"
force_new_fields = ["name"]

[fields]
description = { description = "Description of the group" }
"group-alias" = { description = "A short group alias" }
"user-assignment" = { description = "JSON string defining access permission assignment" }

[read_mapping]
"group_name" = "name"
"group_alias" = "group_alias"
"description" = "description"
