[resource]
name = "akeyless_ssh_cert_issuer"
description = "Manages an SSH certificate issuer"
category = "secret"

[crud]
create_endpoint = "/create-ssh-cert-issuer"
create_schema = "createSSHCertIssuer"
update_endpoint = "/update-ssh-cert-issuer"
update_schema = "updateSSHCertIssuer"
read_endpoint = "/describe-item"
read_schema = "describeItem"
read_response_schema = "Item"
delete_endpoint = "/delete-item"
delete_schema = "deleteItem"

[identity]
id_field = "name"
import_field = "name"
force_new_fields = ["name", "signer-key-name"]

[fields]
"allowed-users" = { description = "Users allowed to fetch the certificate, e.g. root,ubuntu" }
delete_protection = { type_override = "bool", description = "Enable delete protection" }
description = { description = "Description of the object" }
"extensions" = { description = "Signed certificates with extensions, e.g. permit-port-forwarding" }
"external-username" = { description = "Externally provided username [true/false]" }
"fixed-user-claim-keyname" = { description = "Key-name of IdP claim to extract username from (for external-username=true)" }
"host-provider" = { description = "Host provider type [explicit/target]" }
"item-custom-fields" = { skip = true }
"metadata" = { description = "Deprecated - use description" }
"principals" = { description = "Signed certificates with principal, e.g. example_role1,example_role2" }
"secure-access-enable" = { description = "Enable/Disable secure remote access [true/false]" }
"secure-access-enforce-hosts-restriction" = { type_override = "bool", description = "Enforce connections only to listed hosts" }
"secure-access-host" = { description = "Target servers for connections" }
"secure-access-ssh" = { description = "Bastion SSH server, e.g. my.sra-server:22" }
"secure-access-ssh-creds-user" = { description = "SSH username to connect to target server" }
"secure-access-use-internal-ssh-access" = { type_override = "bool", description = "Use internal SSH Access" }
"signer-key-name" = { description = "Key to sign the certificate with" }
tag = { description = "Tags for the SSH cert issuer" }
"ttl" = { description = "Certificate TTL in seconds" }

[read_mapping]
"item_name" = "name"
"item_type" = "type"
"item_metadata" = "description"
"item_tags" = "tags"
"delete_protection" = "delete_protection"
